#!/bin/bash

#This script will go one level deep from the current directory
#and if the child directory is:
#a git repo
#and has modified files
#it will
#print out the directory name
#print out the active branch
#print out the modified files

#passing the -b option will print out the branch name even if
#no modifed files are found

STARTDIR=$PWD
echo -e "\n"

function branch {
  echo ${i:2}
  BRANCH=$(git branch  2> /dev/null | grep '^*')
  echo " ${BRANCH:2}" 
}

if [ "$1" == "--help" ]; then
  echo "This is not very useful help"
fi

for i in `find . -type d -maxdepth 1`
  do 
    {
      cd "$i" || continue
      MODIFIED=$(git status -s --untracked-files=no 2> /dev/null)  
      if [ -n "$MODIFIED" ]; then 
        branch
        echo "$MODIFIED" 
        echo -e "\n"
      elif [ "$1" == "-b" ] || [ "$1" == "--branch" ]; then
        branch
        echo -e "\n"
      fi 
      cd "$STARTDIR"
    }
done
